### ISSUE TITLE
Blog example Kibana dashboard should use nagioscheckbeat-* instead of nagioscheckbeat*

### ISSUE THREAD

**Issue by jerrac** [PhaedrusTheGreek/nagioscheckbeat#1]
When I first tried to load the example dashboard from the blog directory into my Kibana instance, it complained about `nagioscheckbeat*`. Once I modified the file to use `nagioscheckbeat-*` it worked just fine.

**Comment by PhaedrusTheGreek** [comment]
@jerrac ,  I [updated the readme](https://github.com/PhaedrusTheGreek/nagioscheckbeat/commit/26e0af91f2d406ba1abe91314010ec3fcf413306) to recommend that the index pattern gets created as `nagioscheckbeat*` in the first place.

**Comment by jerrac** [comment]
Erm, it's been long enough that I've forgotten the details of what I ran into, but I think that the template file was part of it. https://github.com/PhaedrusTheGreek/nagioscheckbeat/blob/master/etc/nagioscheckbeat.template.json It's still using the -*. So if you load that template, and then use the dashboards with just a *, then I think that there might be issues.

I think a search and replace on https://github.com/PhaedrusTheGreek/nagioscheckbeat/blob/master/blog/kibana-dashboard.json would make a better fix. 

Anyway, just my thoughts.

**Comment by PhaedrusTheGreek** [comment]
@jerrac You're right , that is inconsistent, however note that the `nagioscheckbeat.template.json` pattern actually has no relation whatsoever to the Kibana pattern.
