### ISSUE TITLE
Error running setup -e

### ISSUE THREAD

**Issue by pasqualecapalbo** [PhaedrusTheGreek/nagioscheckbeat#10]
Hi,
ES and Kibana 7.0.0, while running "./nagioscheckbeat setup -e" I get the error

Exiting: Error loading Elasticsearch template: could not load template: couldn't load template: couldn't load json. Error: 400 Bad Request: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  ..................

I attach the complete output of nagioscheck.
[Nagioscheckerror.txt](https://github.com/PhaedrusTheGreek/nagioscheckbeat/files/3251308/Nagioscheckerror.txt)

Thanks,
Lino

**Comment by gittygoo** [comment]
Getting the same problem here

**Comment by PhaedrusTheGreek** [comment]
Support for 7.x is now up:  https://github.com/PhaedrusTheGreek/nagioscheckbeat/releases/tag/7.6.0
