### ISSUE TITLE
Seccomp

### ISSUE THREAD

**Issue by groupzer0** [PhaedrusTheGreek/nagioscheckbeat#13]
I want to upgrade to nagioscheckbeat 7.x but I'm concerned about the apparent need to disable seccomp. 

Why is forking required in 7.x but not in 6.x? Curious about what changed. 

Thanks!

**Comment by PhaedrusTheGreek** [comment]
This is due to the security [changes that were introduced into libbeat 6.4](https://www.elastic.co/blog/brewing-in-beats-seccomp-filters).   Nagioscheckbeat needs to be able to execute the check commands, which is a potential security hazard, but it's been that way all along.
