### ISSUE TITLE
Clarify the relation to nagios

### ISSUE THREAD

**Issue by stdweird** [PhaedrusTheGreek/nagioscheckbeat#2]
(Haven tried it out, but looks promising)
Could you clarify the relation to nagios infrastructure a bit. It looks like this has parts of nrpe (the actual gathering of the data) and the nagios server (control when to run).

**Comment by PhaedrusTheGreek** [comment]
@stdweird ,

There's a detailed description of the architecture here: https://www.elastic.co/blog/a-case-for-self-monitoring-systems

The relation is that Nagios Core is not required, and that _nagioscheckbeat_ simply uses standard Nagios plugins to gather metrics and pump them into Logstash / Elasticsearch.   As discussed [here](https://discuss.elastic.co/t/questions-about-self-monitoring-systems-blog-post/43542/9), Nagios core can be used for Alerting and Dashboarding, but it's not required.

**Comment by stdweird** [comment]
@PhaedrusTheGreek i completely missed the blog post, it's making things very clear (maybe add the url to the README?)
this looks very very useful.
