### ISSUE TITLE
Guide for setup

### ISSUE THREAD

**Issue by joshFive** [PhaedrusTheGreek/nagioscheckbeat#4]
Do you have a setup guide? Working in a docker container, installed go, and glide. 

Go setup docs say to set GOPATH to the project:
`export GOPATH=/opt/nagioscheckbeat-master`
Glide installation requires a bin and src directory:
`mkdir /opt/nagioscheckbeat-master/bin ; mkdir /opt/nagioscheckbeat-master/src`

Glide is now installed so build:
`bin/glide create
bin/glide install --strip-vcs`

This downloads the source into the src/github.com 
So now I have /opt/nagioscheckbeats-master with all the files from the zip, and a second copy in /opt/nagioscheckbeat-master/vendor/github.com/PhaedrusTheGreek/nagioscheckbeat

During go installation I set GOROOT to /usr/local/go, so the downloaded source is expected under this directory, so copy files over: 
`cp -R /opt/nagioscheckbeat-master/vendor/* /usr/local/go/src/. `

So trying to run the main.go:
`go run main.go`

`#github.com/PhaedrusTheGreek/nagioscheckbeat/beater`
`beater/nagioscheckbeat.go:18: undefined: publisher.Client`

**Comment by PhaedrusTheGreek** [comment]
Curious what you are trying to accomplish - do you want to set up a development environment?

**Comment by joshFive** [comment]
I would like to test nagioscheckbeat in my dev elastic stack env.

**Comment by PhaedrusTheGreek** [comment]
What version of the stack are you running?

**Comment by joshFive** [comment]
I'm running 5.5.1

**Comment by PhaedrusTheGreek** [comment]
I updated the README to point out that you can download the appropriate release for your OS from here:

https://github.com/PhaedrusTheGreek/nagioscheckbeat/releases

Installation is very straightforward - just unpack and run.  For example, in RPM, you can do 

```
wget https://github.com/PhaedrusTheGreek/nagioscheckbeat/releases/download/0.6.0/nagioscheckbeat-0.6.0-i686.rpm
rpm -i nagioscheckbeat-0.6.0-i686.rpm
service nagioscheckbeat start
```

or you can install the tar.gz

```
 wget https://github.com/PhaedrusTheGreek/nagioscheckbeat/releases/download/0.6.0/nagioscheckbeat-0.6.0-linux-x86_64.tar.gz
tar xvzf nagioscheckbeat-0.6.0-linux-x86_64.tar.gz
cd nagioscheckbeat-0.6.0-linux-x86_64
./nagioscheckbeat
```

**Comment by PhaedrusTheGreek** [comment]
Let me know if you have any trouble running it against 5.5.1

**Comment by joshFive** [comment]
Perfect! that is exactly what I was missing. Thanks

**Comment by joshFive** [comment]
Everything is working. Thanks
