### ISSUE TITLE
Logstash configration

### ISSUE THREAD

**Issue by mpibpc-mroose** [PhaedrusTheGreek/nagioscheckbeat#5]
Hi,
I stumbled a bit at installation time as the configuration options for Logstash output seem to differ a bit from the "official" beats.

An example: to configure the SSL certificate validation in `filebeat` you have to set
`ssl.verification_mode: none`

and in `nagioscheckbeat`

`tls.insecure: true`

... which could it make a bit difficult for people like me who are using a configuration management and "snippets" for the installation of the beats.

Maybe this could get fixed in a 6.x release?

Best wishes and thanks for the tool,
Marco

**Comment by PhaedrusTheGreek** [comment]
Updated to 6.2.3 today - you should find all configuration is up to date now.
