### ISSUE TITLE
Gathering data of nagios monitored servers

### ISSUE THREAD

**Issue by GautiAM** [PhaedrusTheGreek/nagioscheckbeat#8]
I have installed nagioscheckbeat, data started flowing into elastic search and i see only nagios server metrics there, this beat will not provide the metrics of all the servers which nagios is monitoring?

Does the package has default dashboards as well? because i'm getting no directory error while running "setup -e"

Thanks
Gauti

**Comment by PhaedrusTheGreek** [comment]
That's correct, this tool is not meant to integrate with NagiosCore.
