### ISSUE TITLE
Install nagioscheckbeat

### ISSUE THREAD

**Issue by m2cci-KGY** [PhaedrusTheGreek/nagioscheckbeat#9]
Hi,
I use Shinken to make my monitoring
So It's possible to use nagioscheckbeat with shinken to get some informations on check_disk, check_cpu etc... 
So when I would like to install nagioscheckbeat and I make this command " make setup" or "make"
I get this error :
mkdir -p vendor/github.com/elastic/
cp -R /src/github.com/elastic/beats vendor/github.com/elastic/
cp: cannot stat ‘/src/github.com/elastic/beats’: No such file or directory
make: *** [copy-vendor] Error 1
some one can help me
So thank yopu for your help.

**Comment by PhaedrusTheGreek** [comment]
Hi, building from source should not be necessary.  I have updated the [install docs](https://github.com/PhaedrusTheGreek/nagioscheckbeat/blob/master/README.md#download--install) to show an example of installing on a redhat system.

e.g.:

```
$ sudo rpm -i https://github.com/PhaedrusTheGreek/nagioscheckbeat/releases/download/6.2.3/nagioscheckbeat-6.2.3-i686.rpm
```
